### ISSUE TITLE
error with dependencies install

### ISSUE THREAD

**Issue by jharenza** [d3b-center/medullo-classifier-package#1]
`devtools::install_github("d3b-center/medullo-classifier-package", dependencies = T)` gives error installing, even with dep = T

> ERROR: dependencies 'GSVA', 'preprocessCore' are not available for package 'medulloPackage'
> * removing '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/medulloPackage'
> Error: Failed to install 'medulloPackage' from GitHub:
>   (converted from warning) installation of package '/var/folders/zs/8g7y6mfs7lldb27t4w906hj1z51wzr/T//RtmprHffjh/file1a136d7a0e71/medulloPackage_0.1.0.tar.gz' had non-zero exit status

**Comment by jharenza** [comment]
Same error upon git clone install:

> $ git clone https://github.com/d3b-center/medullo-classifier-package.git
> Cloning into 'medullo-classifier-package'...
> remote: Enumerating objects: 147, done.
> remote: Counting objects: 100% (147/147), done.
> remote: Compressing objects: 100% (87/87), done.
> remote: Total 406 (delta 82), reused 121 (delta 60), pack-reused 259
> Receiving objects: 100% (406/406), 62.11 MiB | 1.09 MiB/s, done.
> Resolving deltas: 100% (170/170), done.
> $ R CMD INSTALL --no-multiarch --with-keep.source medullo-classifier-package
> * installing to library ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’
> ERROR: dependencies ‘GSVA’, ‘preprocessCore’ are not available for package ‘medulloPackage’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/medulloPackage’

**Comment by komalsrathi** [comment]
resolved
